# Computational replication {#computational}

Do the authors' results replicate?

1. Using the authors own code as provided?

2. When we re-check their data cleaning and feature construction?

## Data sourcing and code structure


## Cleaning and reconstruction

We recode the construction of the data used in the analysis in chapter \ref{recode}.

## 'Stata' part of code

> Re-run Stata analysis code and see if it generates the numbers reported in the text [DONE] (looks good)

Source and documentation: 

Florian re-ran the do files as found in ['original files'](https://github.com/ashlab11/ReplicationGames/tree/main/OriginalFiles)

 
> "From_Survey_To_Replication_Dataset.do": contains the Stata commands that allow to create Replication_Dataset.dta, starting from Survey.dta.

> "Replication_Code_Stata.do": contains the Stata commands that allow to replicate all the results presented in the paper. It is organized by tables.

(?All results or just regressions?)

The `.do` file doesn't create tables, it just generates a log file

Tables 2-5. Florian scanned it, saw the results looked similar; same coefficients and standard errors. [Note: this could also be checked in chatgpt.]

See the log file: [`stata_replication_log_20240419.log`](https://github.com/ashlab11/ReplicationGames/commit/c1c70a0f037e0fdfda7405dc0a089fee74f281cb#diff-0caf70398d5ec3d3683924f8a14046b5d176dc8b4a95f3aaabdadd96b9243390)

## R part of the code




