# Overview and approach 

## Key details

"The Political Consequences of Green Policies"

Authors: ...

Our 'writeup' will be given in the chapter "[A comment on Colantone et al. (2024, APSR)](#writeup).

## Background and goalss

We are 'robustness replicating' @colantone2024political (also noting @colantone2024political_cor) for a replication game (see [Institute for replication](i4rep.org))

Main goals

1.  Computationally reproduce key results (do they computationally hold up, especially the 'main claims'). See ['Computational replication'](#computational).

2.  Robustness checks: Consider alternate plausible specifications and approaches. Do the results persist? See ['Robustness checks'](#robustness)

Aspirational: critique methodology, provide further analysis (e.g., multiple hypothesis testing corrections, equivalence tests)

## The paper's main claim, evidence

###  **Main claim:**

 \~\'This policy caused people \[who were financially hurt\] to vote for Lega\'. \[or more generally to be more right wing\]

Background: \"The policy identifies the most polluting categories of vehicles and bans them from accessing and circulating within the area.\"

### **Main evidence for this claim:** 

> the difference in the differences of outcomes by emission category, that is, between Diesel versus Petrol owners of Euro4, and Diesel versus Petrol owners of Euro5.\"

Note it's a difference in differences without a time dimension, although they later consider vote switches.


> Our main dependent variable is an indicator that takes the value 1 if the respondent reports voting for Lega, and 0 otherwise.

> the average estimated effect is 13.5 percentage points ... the baseline rate of support for Lega in the sample was 24.4%. ... owning a car affected by the vehicle ban raised the probability of voting for Lega in the subsequent elections by 55% above the baseline rate\"

### **Secondary claim(s)/other key claims:** 

> electoral change did not stem from a broader shift against environmentalism, but rather from disaffection with the policy\'s uneven pocketbook implications

They also, \~'people who were *compensated* did *not* shift in response to the policy'.

These are implicitly claims of (1) null or bounded effects and (2) *differential* effects (for those compensated vs. those not compensated.) This is important to the authors' theoretical interpretation of the effect, and its generalization to political behavior as a whole.
